[package]
name = "conversation_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
reqwest = "0.12.8"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
crossterm = "0.28.1"